### ISSUE TITLE
Get and Set dynamic functions unusable on engine native components when trying to get float variables

### ISSUE THREAD

**Issue by naielex** [colory-games/UEPlugin-AccessVariableByName#33]
**System Information**
  
* OS: Windows
* Unreal Engine version: 5.0-5.1
* Plugin version: 1.2.0 

**Expected behavior**  
Get a float variable from a component such as a light component's intensity. Same for set.

**Description about the bug**  
The variable cannot be found with the dynamic node, the normal one does find it as expected. I'm expecting it to be due to the difference in precision (single vs double).

**Screenshots/Logs** [Optional]  
Setup with both the functions, showing the issue that the normal "get variable by name" find a single precision float, while in the dynamic you're only able to select a double precision float. Output log print of the result of both.
https://prnt.sc/GSU94Ehd47pn

**Comment by nutti** [comment]
@naielex 

Thanks for your report.
I confirmed this issue on my environment.
We will tackle to fix this issue from now.
