### ISSUE TITLE
Crashes on Quest

### ISSUE THREAD

**Issue by GuillaumeCoteArcadia** [colory-games/UEPlugin-AccessVariableByName#40]
**System Information**
  
* OS: Quest Pro (Android)
* Unreal Engine version: 5.1
* Plugin version: Nov 7, 2022

**Expected behavior**  
I expect to be able to call set variable by name (dynamic) or the get variable by name (Dynamic) node on a quest headset the same way I call it in the editor and get the same result.

**Description about the bug**  
When I run the same code that works in editor on my quest it crashes the app.

**Screenshots/Logs** [Optional]  
![image](https://github.com/colory-games/UEPlugin-AccessVariableByName/assets/80729550/1d194673-f751-411f-a995-23f6cee0f64f)

**Additional comments** [Optional]
Thanks for making this. It is an Incredible idea and product, I hope we can make it work on quest!

**Comment by nutti** [comment]
From the discord discussion, this issue is not valid due to the workflow change of the author.
Close this issue for now.
