### ISSUE TITLE
Get the value of a member in the structure in a map, fail

### ISSUE THREAD

**Issue by QTHunYuan** [colory-games/UEPlugin-AccessVariableByName#44]
**System Information**
  
OS: [Windows 10 Pro]
Unreal Engine version: [e.g. 5.1.0]
Plugin version: [e.g. 1.4.0]

**Expected behavior**  
*The behavior you expect about the feature you reported.*

I created a blueprint map, just like： TMap<FName, CustomStruct>Map. There is a float member named HP in CustomStruct .When I use the Get node and use the parameter (Map ["Body"]. HP), the Get node can correctly display the HP pin and float type, but get the value of HP fails.

**Description about the bug**  
*The description about the bug.*

**Screenshots/Logs** [Optional]  
*It is good to solve the bug if you attach screenshots or logs (like crash report).*
1,CustomStruct
![Struct](https://github.com/colory-games/UEPlugin-AccessVariableByName/assets/93028263/976f2f4c-1b2e-4596-8007-a6e1ec7f1c3f)

2,BluePrint
![GetNode](https://github.com/colory-games/UEPlugin-AccessVariableByName/assets/93028263/69bf9974-1c06-43f5-b188-fa164de56424)

3,Result
![PlayResult](https://github.com/colory-games/UEPlugin-AccessVariableByName/assets/93028263/56e5bc0c-4557-4405-a1df-3b6977c1c5ea)

**Additional comments** [Optional]

**Comment by QTHunYuan** [comment]
I added the structure name but still failed.
![插件问题03](https://github.com/colory-games/UEPlugin-AccessVariableByName/assets/93028263/c032e1f3-edda-40eb-99c2-6a7ccac24d21)

**Comment by nutti** [comment]
@QTHunYuan 

Current version does not support to access a map variable with Name-type key.
You can only access it with String-type key.
Does it meet your requirement?

**Comment by QTHunYuan** [comment]
Understood, thank you.

**Comment by nutti** [comment]
This issue is now fixed.
Next version supports FName as a map key.

**Comment by QTHunYuan** [comment]
This is good news, thank you very much.




***@***.***
***@***.***







                       
原始邮件
                       
                     

发件人："nutti"< ***@***.*** &gt;;

发件时间：2024/3/21 18:12

收件人："colory-games/UEPlugin-AccessVariableByName"< ***@***.*** &gt;;

抄送人："QTHunYuan"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [colory-games/UEPlugin-AccessVariableByName] Get the value of amember in the structure in a map, fail (Issue #44)




 
This issue is now fixed.
 Next version supports FName as a map key.
