### ISSUE TITLE
Dynamic version Node Failed

### ISSUE THREAD

**Issue by QTHunYuan** [colory-games/UEPlugin-AccessVariableByName#46]
**System Information**
  
OS: [ Windows 10 Pro]
Unreal Engine version: [5.1.0]
 Plugin version: [1.4.0]

**Expected behavior**  
*The behavior you expect about the feature you reported.*

**Description about the bug**  
CustomisStruct contains some floats.
When obtaining data from TMap<FString, CustomStruct>TestMap, the normal version was successful, but the dynamic version node failed. The project requires the use of a dynamic version, and we hope it can be fixed. Thank you!

**Screenshots/Logs** [Optional]  
*It is good to solve the bug if you attach screenshots or logs (like crash report).*
1，struct
![插件问题06](https://github.com/colory-games/UEPlugin-AccessVariableByName/assets/93028263/359a1ce8-12dd-4526-b540-75cee12edcd6)

2，the normal version was successful
![插件问题04](https://github.com/colory-games/UEPlugin-AccessVariableByName/assets/93028263/f0dc6bf6-ce5d-4d73-abef-a83a95a3b605)

3，the dynamic version node failed
[
![插件问题07](https://github.com/colory-games/UEPlugin-AccessVariableByName/assets/93028263/218f13b8-3961-4bc4-8f7c-f208d13499d5)
](url)

**Additional comments** [Optional]

**Comment by nutti** [comment]
@QTHunYuan 

Does this issue occur on your environment now?
I could not reproduce your issue.

**Comment by QTHunYuan** [comment]
The structure I created in C++has a default float type. I noticed the blueprint debug information, where regular nodes are displayed as single precision and dynamic nodes are displayed as double precision, so perhaps it is the problem caused by the conversion between single precision and double precision?

**Comment by nutti** [comment]
@QTHunYuan 

> so perhaps it is the problem caused by the conversion between single precision and double precision?

Yes, the dynamic node must specify the single or double precision for float type variable.

**Comment by QTHunYuan** [comment]
Can you modify the dynamic node or add a special dynamic node that can automatically recognize single precision and double precision float? Because in many cases, it is uncertain which type of float to obtain.

**Comment by QTHunYuan** [comment]
This way, it can be automatically processed. Thank you !

![变量插件节点](https://github.com/colory-games/UEPlugin-AccessVariableByName/assets/93028263/b0a6699a-41c1-4eb9-9347-927de2eb961c)

**Comment by QTHunYuan** [comment]
Now I have found a way to automatically process it, which I didn't expect to do before.

[
![插件问题08](https://github.com/colory-games/UEPlugin-AccessVariableByName/assets/93028263/95794e2d-1d5a-478d-aed4-e5acf2623fa6)
](url)

**Comment by nutti** [comment]
@QTHunYuan 

Good to hear this.
I think modifying the dynamic node to recognize the precision automatically is difficult.
Please use your workaround for now. Your workaround seems to work well.
